Rework vhdl data type
dalex78/vunit pull request #1
Opened 2022-04-23 11:43 UTC by dalex78

The proposed modifications on the `codec` package are retro-compatible. The `tb_codec.vhd` has not been modified to prove this.
Here is a list of changes:

 + Add comments into the code. Add a page in documentation which show the declaration package of the `codec.vhd`.
 + Removed hard coded value (the encode)
 + Replace the type 'string' used to encode by an alias named 'code_t' to ease readability and maintainbility.
 + Inverse the `function` and alias `names` to ease readability and maintainbility:
   ```vhdl
   function encode (constant code : std_ulogic_vector) return string;
   function decode (constant code : string) return std_ulogic_vector;
   alias encode_std_ulogic_vector is encode[std_ulogic_vector return string];
   alias decode_std_ulogic_vector is decode[string return std_ulogic_vector];
   ```
 + The code length for integer automatically adapts to the width of the integer (1993/2002/2008: 32bits, 2019: 64bits)
 + Functions `encode_array_header` and `get_range` are replaced (these names are not consistent with the other functions):
   - `function encode_range(range_left : integer; range_right : integer; is_ascending : boolean) return code_vec_t;`
   - `function decode_range(code : code_vec_t) return range_t;`
   - `encode_array_header` and `get_range` are deprecated but preserved for backward compatibility.
   - `encode_array_header` and `get_range` take the encoded string of `range_left`, `range_right` and `is_ascending` while `encode_range` and `decode_range` directly take integers and a boolean.
   - Note that `encode_array_header` can encode two ranges but it was never used for that purpose (anywhere in the VUnit repo). The `encode_range` can only encode a single range.
 + Replace the `ieee.numeric_std.unsigned` by `ieee.numeric_std.unresolved_unsigned`
 + Replace the `ieee.numeric_std.signed` by `ieee.numeric_std.unresolved_signed`
 + Simplify the local `log2` function used to encode the  `real` type by using the `ieee.math_real` package.
 + The type `std_ulogic_array` is similar to the `std_ulogic_vector` but with an integer range. However, it was not the case for bit_vector. There is now a type `bit_array` for that purpose.
   The same idea could be applied to `string`, but I did not see the use case so it was not implemented.
 + For each encoded type which are a `scalar`, an `enumerated type` or a `records type`, there is a constant named `code_length_type_name` which indicate how many character are needed to encode a value of the selected type.
 + For each encoded type which an `array type`, there is a function named `function code_length_type_name(length : natural) return natural;` which indicate how many character are needed to encode a value of the selected type.
 + The function `to_byte_array` and `from_byte_array` are replaced (these names are not consistent with the other functions and the introduction of `bit_array` required a change of `bit_vector` to `bit_array`):
   - `function encode_raw_bit_array(data : bit_array) return code_t;`
   - `function decode_raw_bit_array(code : code_t) return bit_array;`
   - `to_byte_array` and `from_byte_array` are deprecated but preserved for backward compatibility.

 + Move the declaration of the type `std_ulogic_array` from `codec_builder.vhd` to `types.vhd` ? TBC
 +
 + Have the `encode` and `decode` function closer to one another.
 + Move the `get_simulator_resolution` function out of `codec_builder.vhd` ? TBC and where ?

TODO checker que les noms de paramètres n'ont pas changé.

2022-04-23 11:51 UTC, std-max commented on vunit/vhdl/data_types/src/codec-2008p.vhd
> +-- This package contains support functions for standard codec building
I would have explained that this is only for VHDL2008

2022-04-23 12:57 UTC, std-max requested changes
Very nice

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec-2008p.vhd
> +-------------------------------------------------------------------------------
Ok for me, but it seems that this separator (PACKAGE DECLARATION) is not widely used accross VUnit ?

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec-2008p.vhd
> +  --===========================================================================
I would have used -------- instead of --============== to be consistent with what have been previously used

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec-2008p.vhd
> +  --===========================================================================
Should we group apart encoded and decoded functions together or should we group functions by pair of (encode, decode) ?
Just asking, no idea...

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec.vhd
> +  -- Remark: this package encode any predefined type into a string, however, this
this package encodeS

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec.vhd
> +  -- between VUnit version.
I dont understand what this comment means

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec.vhd
> +  -- All data going through the encoding process becomes a string: it is
it * basically becomes

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec.vhd
> +  function encode_std_ulogic_vector(data : std_ulogic_vector) return code_t;
Might be a dummy question:
Would it be possible to use encode_std_ulogic_array in place of encode_std_ulogic_vector ?

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec.vhd
> +  --===========================================================================
same comment about separator styling

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec.vhd
> +    variable code  : code_t(1 to code_length_range_type);
for consistency: maybe code sould be rename to ret_val ?

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec.vhd
> +  function get_range(code : code_t) return range_t is
I dont have dived into details.
Is it possible to use encode_range or decode_range inside get_range function ?
That would remove dupplicated code.

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec.vhd
> +    severity warning;
I would have kept VUnit assertion style

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder-2008p.vhd
> +  -- If you need to retrieve the length of the encoded data whitout,
Typo: without

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder-2008p.vhd
> +    for i in data'range loop
This can be shorter and idiomatic. Is this deliberate ?

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder-2008p.vhd
> +        result(i) := true;
This can be shorter and idiomatic. Is this deliberate ?

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder-2008p.vhd
> +  procedure encode_integer_vector(constant data : in integer_vector; variable index : inout code_index_t; variable code : out code_t) is
so here in codec_builder, functions encode and decode are grouped by types
that was not the case in codec package
I think this should be consistent

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +use ieee.std_logic_1164.all;
I would have put std_logic_1164 in first

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- Remark: this package encode any predefined type into a string, however, this
encodeS*

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- A character (string of length 1) stores value on 8 bits
A character (string of length 1) is 8-bit long

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- A character (string of length 1) can store up to 2**8 = 256 value
256 valueS*

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- of ieee.std_ulogic) with an integer range, you can use the type 'std_ulogic_array'
comments are reversed for std_ulogic and bit

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- Encoding length for each types
each type*

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- If you need to retrieve the length of the encoded data whitout,
without*

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- The formulation "type'pos(type'right) + 1" gives the number of symbols defined by the enumerated type
is symbol the appropriate term ?
It might be, but I dont remember what is written in the LRM

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- A 'time' type is encoded TBC
tbc

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- The 'index' is update by the procdeures in order for the next encode/decode
is updated*
by the procedures*

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- procedure to be abla to keep encoding or decoding the data without having to deal
to be able*

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  alias code_index_t is integer;
integer ok
as code_t is a string, shoud we replace integer by positive ?

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- A range is constituted of two bounds (an left bound and a right bound)
a* left

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- range is of lenght 1 or when the range is null
Explain in the comment that
left bound and right bound are encoded as integers
direction of the array is encoded as a boolean

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- Note, there is no procedure 'decode_range' because we want to retireve an unknown range.
retrieve*

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- must be constrained. This contradict the purpose of the functionnality.
contradictS

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- There are a 'decode_range' function inside the codec.vhd package
There is* a

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- We define two functions which encode a 'bit_vector' or a 'std_ulogic_vector' without its range.
without their

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +    code(index) := std_ulogic'image(data)(2);
I think branching with a switch-case is less expensive than slicing array

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +    result := std_ulogic'value("'" & code(index) & "'");
switch case here ? i dont know
or maybe like after:
character'val(severity_level'pos(data))

2022-04-23 12:57 UTC, std-max commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- TODO Remove hard coded values (EXPONENT, MANTISSE and SIGN width constants are defined in the common_pkg)
TODO

2022-04-23 13:13 UTC, dalex78 commented on vunit/vhdl/data_types/src/codec-2008p.vhd
> +-------------------------------------------------------------------------------
Removed

2022-04-23 13:14 UTC, dalex78 commented on vunit/vhdl/data_types/src/codec-2008p.vhd
> +  --===========================================================================
--====== are used as "big" separator while -------- is used as "smaller" separator.

2022-04-23 13:17 UTC, dalex78 commented on vunit/vhdl/data_types/src/codec.vhd
> +  function encode_std_ulogic_vector(data : std_ulogic_vector) return code_t;
Yes it is possible

2022-04-23 13:22 UTC, dalex78 commented on vunit/vhdl/data_types/src/codec.vhd
> +    variable code  : code_t(1 to code_length_range_type);
Yes
TODO

2022-04-23 13:23 UTC, dalex78 commented on vunit/vhdl/data_types/src/codec.vhd
> +  function get_range(code : code_t) return range_t is
Yes, that's is done

2022-04-23 13:29 UTC, dalex78 commented on vunit/vhdl/data_types/src/codec_builder-2008p.vhd
> +  procedure encode_integer_vector(constant data : in integer_vector; variable index : inout code_index_t; variable code : out code_t) is
Procedure are grouped together while functions are not. It could be improved

2022-04-23 13:32 UTC, dalex78 commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +use ieee.std_logic_1164.all;
done

2022-04-23 13:34 UTC, dalex78 commented on vunit/vhdl/data_types/src/codec_builder.vhd
> +  -- The formulation "type'pos(type'right) + 1" gives the number of symbols defined by the enumerated type
'elements' could be used

2022-04-30 20:52 UTC, dalex78 commented
Closed. PR only for discussion with std_max

2022-04-30 20:53 UTC, closed without merging